### ISSUE TITLE
Implement Product Search

### ISSUE THREAD

**Issue by peter-gerhard** [sphereio/sphere-sunrise-dmexco#54]

**Comment by peter-gerhard** [comment]
@trangng @lauraluiz should it be possible to search a product inside a category?

**Comment by lauraluiz** [comment]
So you mean searching for "shoes" and receiving all products in this category?
I would go simple and just use the `ProductProjectionSearch.withText` functionality, that allows a full-text search for the given text.

**Comment by trangng** [comment]
@peter-gerhard if someone searches for "jacket" and it's already in the category "shoes" then we should show all results, that are related to "jacket" and not only in the current category, because then we wouldn't have any search results. 

on category pages customer will use filter to narrow down their product results.

**Comment by peter-gerhard** [comment]
ok
