### ISSUE TITLE
Category links not working on mobile

### ISSUE THREAD

**Issue by ct-jensschulze** [sphereio/sphere-sunrise-dmexco#89]
Open the site on a mobile and try to open a category via the menu. After selection no page load is executed.

**Comment by ct-jensschulze** [comment]
Can also be reproduced locally using the Android Emulator by Android Studio.

**Comment by peter-gerhard** [comment]
The problem lies in this piece from the main.js:

// Close hamburger menu on select click or outside
$(function() {
  $('.navbar-collapse ul li a:not(.dropdown-toggle)').bind('click touchstart', function() {
    $('.navbar-toggle:visible').click();
  });
});

when commenting out the  $('.navbar-toggle:visible').click(); it works. but has to be checked if there are some side effects.

**Comment by JulianSamarjiev** [comment]
@peter-gerhard Cleaned up the code that was braking, thanks for pointing it out. Would appreciate if you add such issues that are assigned to me in the design repo :+1:
